name: Build Container on Push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'bump:') && github.ref_name == 'main'"
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    name: "Bump version, create changelog, build container, push to GHCR"
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - id: cz
        name: Bump version and create changelog
        uses: commitizen-tools/commitizen-action@a49cac8e98f3954a16e107f026f71cf84b17706c  # v0.23.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{GITHUB_REPOSITORY}}:${{steps.cz.outputs.version}} .
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{GITHUB_REPOSITORY}}:${{steps.cz.outputs.version}}
